# Generated by Django 3.0.7 on 2020-07-23 02:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follow_to',
            field=models.ManyToManyField(blank=True, related_name='follow_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
